# Generated by Django 3.1.7 on 2021-04-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redditor",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Subreddit",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("display_name", models.CharField(default="", max_length=30)),
                ("title", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyRedditorScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score_type",
                    models.CharField(
                        choices=[("SUB", "Submission"), ("COM", "Comment")],
                        max_length=3,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rank", models.PositiveIntegerField()),
                ("week_number", models.PositiveIntegerField()),
                ("created_utc", models.DateTimeField()),
                (
                    "redditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reddit.redditor",
                    ),
                ),
                (
                    "subreddit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reddit.subreddit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("karma", models.IntegerField()),
                ("upvote_ratio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("num_comments", models.IntegerField()),
                ("created_utc", models.DateTimeField()),
                (
                    "redditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reddit.redditor",
                    ),
                ),
                (
                    "subreddit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reddit.subreddit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("karma", models.IntegerField()),
                ("created_utc", models.DateTimeField()),
                (
                    "redditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reddit.redditor",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reddit.submission",
                    ),
                ),
                (
                    "subreddit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reddit.subreddit",
                    ),
                ),
            ],
        ),
    ]
